var data = {
    "monthSalsePickPart": [{                                      //
        "no": "1",                                            
        "title": "中国",                                  
        "value": "27033.28",                                  
        "percent": "0.1131"                                   
    }, {
        "no": "2",
        "title": "美国",
        "value": "24720.035",
        "percent": "0.1034"
    }, {
        "no": "3",
        "title": "意大利",
        "value": "19262.9689",
        "percent": "0.0806"
    }, {
        "no": "4",
        "title": "德国",
        "value": "16135.5",
        "percent": "0.0675"
    }, {
        "no": "5",
        "title": "法国",
        "value": "13928.501",
        "percent": "0.0583"
    }, {
        "no": "6",
        "title": "瑞典",
        "value": "12956.44",
        "percent": "0.0542"
    }, {
        "no": "7",
        "title": "日本",
        "value": "9267.193",
        "percent": "0.0388"
    }, {
        "no": "8",
        "title": "澳大利亚",
        "value": "8965",
        "percent": "0.0375"
    }, {
        "no": "9",
        "title": "菲律宾",
        "value": "8830",
        "percent": "0.0369"
    }, {
        "no": "10",
        "title": "泰国",
        "value": "7183.602",
        "percent": "0.0301"
    }, {
        "no": "11",
        "title": "其他",
        "value": "9071111.678",
        "percent": "0.9796"
    }],
    "monthSalsePickPrePart": [{                          //
        "diff": "62206.96",                          //
        "detail": [{                                 
            "title": "十二月",
            "value": "62206.96"
        }, {                                 
            "title": "十一月",
            "value": "3212"
        }, {                                 
            "title": "十月",
            "value": "1234"
        }, {                                 
            "title": "九月",
            "value": "2134"
        }, {                                 
            "title": "八月",
            "value": "1233"
        },{                                 
             "title": "七月",
             "value": "2222"
        },{                                 
             "title": "六月",
             "value": "1111"
        },{                                 
             "title": "五月",
             "value": "3333"
        },{                                 
             "title": "二月",
             "value": "4444"
        },{
             "title": "三月",
             "value": "6365.7"
        },{
             "title": "四月",
             "value": "27033.28"
        },{
            "title": "五月",
            "value": "17033.28"
        }],
        "title": "中国"                          
    }, {
        "diff": "28454.945",
        "detail": [{
            "title": "十一月",
            "value": "1412.828"
        }, {
            "title": "十二月",
            "value": "18742.913"
        }, {
            "title": "一月",
            "value": "9907.629"
        }, {
            "title": "二月",
            "value": "20097.692"
        }, {
            "title": "三月",
            "value": "28454.945"
        }, {
            "title": "四月",
            "value": "24720.035"
        }],
        "title": "美国"
    }, {
        "diff": "19262.9689",
        "detail": [{
            "title": "十一月",
            "value": "705.2124"
        }, {
            "title": "十二月",
            "value": "2946.0231"
        }, {
            "title": "一月",
            "value": "17468.1221"
        }, {
            "title": "四月",
            "value": "19262.9689"
        }],
        "title": "意大利"
    }, {
        "diff": "16135.5",
        "detail": [{
            "title": "四月",
            "value": "16135.5"
        }],
        "title": "德国"
    }, {
        "diff": "19611.642",
        "detail": [{
            "title": "十一月",
            "value": "12254.639"
        }, {
            "title": "十二月",
            "value": "6736.651"
        }, {
            "title": "一月",
            "value": "19611.642"
        }, {
            "title": "二月",
            "value": "939.49"
        }, {
            "title": "三月",
            "value": "18000.511"
        }, {
            "title": "四月",
            "value": "13928.501"
        }],
        "title": "法国"
    }, {
        "diff": "12956.44",
        "detail": [{
            "title": "四月",
            "value": "12956.44"
        }],
        "title": "瑞典"
    }, {
        "diff": "23599.787",
        "detail": [{
            "title": "十一月",
            "value": "23599.787"
        }, {
            "title": "十二月",
            "value": "11664.179"
        }, {
            "title": "一月",
            "value": "16.99"
        }, {
            "title": "三月",
            "value": "1645.586"
        }, {
            "title": "四月",
            "value": "9267.193"
        }],
        "title": "日本"
    }, {
        "diff": "8965",
        "detail": [{
            "title": "十一月",
            "value": "359.17"
        }, {
            "title": "十二月",
            "value": "1440"
        }, {
            "title": "一月",
            "value": "1721"
        }, {
            "title": "三月",
            "value": "5648"
        }, {
            "title": "四月",
            "value": "8965"
        }],
        "title": "澳大利亚"
    }, {
        "diff": "10034",
        "detail": [{
            "title": "十一月",
            "value": "1834.23"
        }, {
            "title": "十二月",
            "value": "10034"
        }, {
            "title": "一月",
            "value": "6488"
        }, {
            "title": "二月",
            "value": "1302"
        }, {
            "title": "三月",
            "value": "5007"
        }, {
            "title": "四月",
            "value": "8830"
        }],
        "title": "菲律宾"
    }, {
        "diff": "7183.602",
        "detail": [{
            "title": "三月",
            "value": "5643.323"
        }, {
            "title": "四月",
            "value": "7183.602"
        }],
        "title": "泰国"
    }, {
        "diff": "0",
        "detail": [],
        "title": "其他"
    }],
    "yearSalsePickPart": [{                   //年度客户提货排名
        "no": "1",                        
        "title": "美国",                
        "value": "257314.072",            
        "percent": "0.1050"               
    }, {
        "no": "2",
        "title": "阿富汗",
        "value": "193748.44",
        "percent": "0.0790"
    }, {
        "no": "3",
        "title": "中国",
        "value": "188382.72",
        "percent": "0.0768"
    }, {
        "no": "4",
        "title": "意大利",
        "value": "140666.40559",
        "percent": "0.0574"
    }, {
        "no": "5",
        "title": "法国",
        "value": "105601.022",
        "percent": "0.0431"
    }, {
        "no": "6",
        "title": "泰国",
        "value": "99250.148",
        "percent": "0.0405"
    }, {
        "no": "7",
        "title": "朝鲜",
        "value": "94729.59",
        "percent": "0.0386"
    }, {
        "no": "8",
        "title": "菲律宾",
        "value": "73458",
        "percent": "0.0300"
    }, {
        "no": "9",
        "title": "印度",
        "value": "72723.8",
        "percent": "0.0297"
    }, {
        "no": "10",
        "title": "德国",
        "value": "66657.03",
        "percent": "0.0272"
    }, {
        "no": "11",
        "title": "其他",
        "value": "1158854.903754",
        "percent": "0.4727"
    }],
    "yearSalsePickPrePart": [{                    //
        "diff": "86060.166",                  
        "detail": [{                          
            "title": "一月",
            "value": "9907.629"
        }, {
            "title": "二月",
            "value": "20097.692"
        }, {
            "title": "三月",
            "value": "28454.945"
        }, {
            "title": "四月",
            "value": "24720.035"
        }, {
            "title": "六月",
            "value": "20066.73"
        }, {
            "title": "七月",
            "value": "11004.697"
        }, {
            "title": "八月",
            "value": "5900.546"
        }, {
            "title": "九月",
            "value": "10031.011"
        }, {
            "title": "十月",
            "value": "16632.052"
        }, {
            "title": "十一月",
            "value": "18538.023"
        }, {
            "title": "十二月",
            "value": "91960.712"
        }],
        "title": "美国"                       
    }, {
        "diff": "29984.16",
        "detail": [{
            "title": "一月",
            "value": "19565.8"
        }, {
            "title": "二月",
            "value": "14284.06"
        }, {
            "title": "三月",
            "value": "39743.04"
        }, {
            "title": "六月",
            "value": "30277"
        }, {
            "title": "七月",
            "value": "29786.96"
        }, {
            "title": "八月",
            "value": "30281.9"
        }, {
            "title": "九月",
            "value": "20050.8"
        }, {
            "title": "十一月",
            "value": "9758.88"
        }],
        "title": "阿富汗"
    }, {
        "diff": "50925.72",
        "detail": [{
            "title": "三月",
            "value": "6365.7"
        }, {
            "title": "四月",
            "value": "27033.28"
        }, {
            "title": "五月",
            "value": "27425.84"
        }, {
            "title": "十月",
            "value": "29995.02"
        }, {
            "title": "十一月",
            "value": "40271.46"
        }, {
            "title": "十二月",
            "value": "57291.42"
        }],
        "title": "中国"
    }, {
        "diff": "30597.56509",
        "detail": [{
            "title": "一月",
            "value": "17468.1221"
        }, {
            "title": "四月",
            "value": "19262.9689"
        }, {
            "title": "六月",
            "value": "14042.7423"
        }, {
            "title": "七月",
            "value": "13537.7489"
        }, {
            "title": "八月",
            "value": "2632.5253"
        }, {
            "title": "十月",
            "value": "18474.33"
        }, {
            "title": "十一月",
            "value": "33230.09039"
        }, {
            "title": "十二月",
            "value": "22017.8777"
        }],
        "title": "意大利"
    }, {
        "diff": "21483.012",
        "detail": [{
            "title": "一月",
            "value": "19611.642"
        }, {
            "title": "二月",
            "value": "939.49"
        }, {
            "title": "三月",
            "value": "18000.511"
        }, {
            "title": "四月",
            "value": "13928.501"
        }, {
            "title": "五月",
            "value": "9423.891"
        }, {
            "title": "七月",
            "value": "9898.511"
        }, {
            "title": "九月",
            "value": "22422.502"
        }, {
            "title": "十月",
            "value": "1000.315"
        }, {
            "title": "十二月",
            "value": "10375.659"
        }],
        "title": "法国"
    }, {
        "diff": "19671.382",
        "detail": [{
            "title": "三月",
            "value": "5643.323"
        }, {
            "title": "四月",
            "value": "7183.602"
        }, {
            "title": "五月",
            "value": "17824.114"
        }, {
            "title": "六月",
            "value": "14400.155"
        }, {
            "title": "七月",
            "value": "6128.982"
        }, {
            "title": "九月",
            "value": "6013.051"
        }, {
            "title": "十月",
            "value": "22177.089"
        }, {
            "title": "十一月",
            "value": "2505.707"
        }, {
            "title": "十二月",
            "value": "17374.125"
        }],
        "title": "泰国"
    }, {
        "diff": "48000",
        "detail": [{
            "title": "六月",
            "value": "43000"
        }, {
            "title": "八月",
            "value": "48000"
        }, {
            "title": "九月",
            "value": "3729.59"
        }],
        "title": "朝鲜"
    }, {
        "diff": "7528",
        "detail": [{
            "title": "一月",
            "value": "6488"
        }, {
            "title": "二月",
            "value": "1302"
        }, {
            "title": "三月",
            "value": "5007"
        }, {
            "title": "四月",
            "value": "8830"
        }, {
            "title": "五月",
            "value": "6951"
        }, {
            "title": "六月",
            "value": "8804"
        }, {
            "title": "七月",
            "value": "8035"
        }, {
            "title": "八月",
            "value": "5319"
        }, {
            "title": "九月",
            "value": "8022"
        }, {
            "title": "十月",
            "value": "3618"
        }, {
            "title": "十一月",
            "value": "2898"
        }, {
            "title": "十二月",
            "value": "8184"
        }],
        "title": "菲律宾"
    }, {
        "diff": "10614",
        "detail": [{
            "title": "一月",
            "value": "6374"
        }, {
            "title": "二月",
            "value": "1062"
        }, {
            "title": "三月",
            "value": "9639"
        }, {
            "title": "四月",
            "value": "6975"
        }, {
            "title": "五月",
            "value": "11676"
        }, {
            "title": "六月",
            "value": "7685"
        }, {
            "title": "七月",
            "value": "6319"
        }, {
            "title": "八月",
            "value": "2003"
        }, {
            "title": "九月",
            "value": "7881"
        }, {
            "title": "十月",
            "value": "5165.8"
        }, {
            "title": "十一月",
            "value": "4740"
        }, {
            "title": "十二月",
            "value": "3204"
        }],
        "title": "印度"
    }, {
        "diff": "24159.72",
        "detail": [{
            "title": "四月",
            "value": "16135.5"
        }, {
            "title": "五月",
            "value": "25103.72"
        }, {
            "title": "六月",
            "value": "12720.31"
        }, {
            "title": "七月",
            "value": "4894"
        }, {
            "title": "九月",
            "value": "2361"
        }, {
            "title": "十月",
            "value": "944"
        }, {
            "title": "十一月",
            "value": "2017.5"
        }, {
            "title": "十二月",
            "value": "2481"
        }],
        "title": "德国"
    }, {
        "diff": "0",
        "detail": [],
        "title": "其他"
    }],
    "monthData": {
        "一月": "01",
        "二月": "02",
        "三月": "03",
        "四月": "04",
        "五月": "05",
        "六月": "06",
        "七月": "07",
        "八月": "08",
        "九月": "09",
        "十月": "10",
        "十一月": "11",
        "十二月": "12"
    },
    "yearData": {
        "2018年": "2018",
        "2017年": "2017",
        "2016年": "2016",
        "2015年": "2015"
    }
}